apiVersion: v1
kind: ConfigMap
metadata:
  name: aks-lab20-wf-config
  namespace: sample-app-namespace-1776656613927
  labels:
    app.kubernetes.io/name: aks-lab20-wf
    kubernetes.azure.com/generator: devhub
data: