apiVersion: v1
kind: Service
metadata:
  name: aks-lab03-wf
  namespace: sample-app-namespace-1776658635524
  labels:
    app.kubernetes.io/name: aks-lab03-wf
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: aks-lab03-wf
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000